# This is a config for E2B sandbox template.
# You can use template ID (0owvxbkl62ounvcsq2xc) or template name (lovable-v0-clone-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-v0-clone-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-v0-clone-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-v0-clone-2')

team_id = "e167cbee-f990-4b6a-b1ee-302f7bc1e542"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-v0-clone-2"
template_id = "0owvxbkl62ounvcsq2xc"
